//Get json data constant
export const SET_EXPENSES = "SET_EXPENSES";
export const SET_EXPENSE_DETAILS = "SET_EXPENSE_DETAILS";
export const ADD_EXPENSE_TO_LIST = "ADD_EXPENSE_TO_LIST";
export const DELETE_EXPENSE = "DELETE_EXPENSE";
export const UPDATE_EXPENSE_TO_LIST = "UPDATE_EXPENSE_TO_LIST";
export const REMOVE_SELECTED_EXPENSES = "REMOVE_SELECTED_EXPENSES";
