//Get json data constant
export const SET_CATEGORIES = "SET_CATEGORIES";
export const SET_CATEGORY_DETAILS = "SET_CATEGORY_DETAILS";
export const ADD_CATEGORY_TO_LIST = "ADD_CATEGORY_TO_LIST";
export const DELETE_CATEGORY = "DELETE_CATEGORY";
export const UPDATE_CATEGORY_TO_LIST = "UPDATE_CATEGORY_TO_LIST";
export const UPDATE_CATEGORY_DETAILS = "UPDATE_CATEGORY_DETAILS";
export const POPULATE_REMAINING_AMOUNT = "POPULATE_REMAINING_AMOUNT";
export const RETURN_REMAINING_AMOUNT = "RETURN_REMAINING_AMOUNT";
export const REMOVE_SELECTED_CATEGORY = "REMOVE_SELECTED_CATEGORY";
